server:
  port: 9094
  
spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: restaurant-db
#      username: username_value  (optional)
#      password=password_value (optional)
#      uri: mongodb://your_username:your_password@localhost:27017/demo
      uri: mongodb://localhost:27017/restaurant-db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka